projectName: training-reference
image: jembi/cdr-training
logPath: /tmp/logs

packages:
  - reverse-proxy
  - openhim
  - hapi-fhir
  - kafka
  - hapi-proxy
  - kafka-mapping-consumer
  - elasticsearch
  - kibana

profiles:
  - name: training
    packages: 
      - reverse-proxy
      - openhim
      - hapi-fhir
      - kafka
      - hapi-proxy
      - elasticsearch
      - kafka-mapping-consumer
      - kibana
    dev: true
    only: false