projectName: training-reference
image: jembi/cdr-training
logPath: /tmp/logs

packages:
  - reverse-proxy
  - openhim
  - hapi-fhir
  - kafka
  - hapi-proxy
  - kafka-mapping-consumer

profiles:
  - name: training
    packages: 
      - reverse-proxy
      - openhim
      - hapi-fhir
      - kafka
      - hapi-proxy
    dev: true
    only: false