version: '3.9'

services:
  hapi-proxy:
    image: jembi/springproxyserver:20211217-170809.3f57ef5
    networks:
      openhim:
      kafka:
      hapi-fhir:
    environment:
      HAPI_SERVER_URL: ${HAPI_SERVER_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOSTS}
      HAPI_SERVER_VALIDATE_FORMAT: ${HAPI_SERVER_VALIDATE_FORMAT}

networks:
  openhim:
    name: openhim_public
    external: true
  kafka:
    name: kafka_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true