version: '3.9'

services:
  reverse-proxy:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 5000
        published: 5000
        mode: host
      - target: 5001
        published: 5001
        mode: host
      - target: 8080
        published: 8080
        mode: host
      - target: 5601
        published: 5601
        mode: host
      - target: 9000
        published: 9000
        mode: host